print("How old are you?", end=' ')
age= input()
print("How tall are you?", end=' ')
heigh = input()
print("How much do you weigh?", end=' ')
weigh = input()
print(f"So, you're {age} old, {heigh} tall and {weigh} heavy.")
